# Generated by Django 4.2.5 on 2023-09-26 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_post_slug_comment'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='comment',
            name='blog_commen_created_79f39f_idx',
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['-created', 'post'], name='blog_commen_created_430b23_idx'),
        ),
    ]
